version: '3.8'
services:
  cfdns:
    image: aiastia/cloudflare-dnsswitch
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
    #command: python main.py
    command: python check_once.py
